logging:
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off
    root: INFO
    searchengine.init: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.boot: info
    org.hibernate.transaction: debug
    org.springframework.transaction: debug
  file:
    name: /home/norrak/Рабочий стол/logi/logfile.log
  loggers:
    additivity: false
    org.hibernate.SQL:
      level: debug
      appenders: [Console]
    org.springframework.boot:
      level: info
      appenders: [Console]
    searchengine.init:
      level: debug
      appenders: [Console]

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Radiomv.ru
    - url: https://ipfran.ru
      name: Ipfran.ru

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: ytafhbfy
    url: jdbc:mysql://localhost:3306/search_engine
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 0  # Отключаем тайм-аут соединения
      idle-timeout: 60000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
        connection:
          provider_disables_autocommit: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  transaction:
    default-timeout: -1  # Убираем тайм-аут транзакции
    rollback-on-commit-failure: true

