logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.boot: info
  file:
    name: /home/norrak/Рабочий стол/logi/logfile.log
  loggers:
    additivity: false
    org.hibernate.SQL:
      level: debug
      appenders: [Console]
    org.springframework.boot:
      level: info
      appenders: [Console]



indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Radiomv.ru
    - url: https://ipfran.ru
      name: Ipfran.ru

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: ytafhbfy
    url: jdbc:mysql://localhost:3306/search_engine
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false




