mysqld:
  log_output: TABLE

logging:
  level:
    root: warn
  appenders:
    Console:
      name: Console
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    File:
      name: File
      fileName: logs/myapp.log
      append: true
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  loggers:
    Root:
      level: debug
      AppenderRef:
        - ref: Console
        - ref: File

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Radiomv.ru
    - url: https://ipfran.ru
      name: Ipfran.ru

server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    username: root
    password: ytafhbfy
    url: jdbc:mysql://localhost:3306/search_engine
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false

